permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "deploy.sh",
    "aero-deploy.tar.gz",
    "aero-debug.log",
  ]

# jekyll-polyglot config
languages: ["en", "es", "de", "fr"]
default_lang: "en"
exclude_from_localization: ["assets"]
data_dir: ./_data

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
